name: 'Debug Analysis'
description: 'Debug Analysis'
inputs:
  codeql-path:
    description: 'Path to the CodeQL executable'
    required: false
  language:
    description: 'Language of the database to analyze'
    required: true
  db-path:
    description: 'Path to the database for which to emit debug infos'
    required: false
runs:
  using: "composite"
  steps:
    - name: test
      run: |
        python3 "${{ github.action_path }}/process.py" "${{ inputs.language }}" "${{ github.repository }}" "${{ github.sha }}" "${{ inputs.codeql-path }}" "${{ inputs.db-path }}" "" ""
      shell: bash
