name: "Action Test"
on: [push]

jobs:
  debug:
    name: CodeQL Debug Analysis Job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      id: codeqlinit
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - run: |
        echo "nothing to do here"
        echo codeql-path ${{ steps.codeqlinit.outputs.codeql-path }}
      shell: bash

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
